image: quay.io/natesime/dolfin_dg:master
clone:
  depth: 1
  
pipelines:
  default:
    - step:
        script:
          - cd ${BITBUCKET_CLONE_DIR}
          - python3 setup.py install
          - cd test/unit/
          - py.test-3